version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: user-service
    restart: always
    environment:
      POSTGRES_DB: user-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"