hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost:5432/your_database
hibernate.connection.username=your_username
hibernate.connection.password=your_password

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

hibernate.show_sql=true
hibernate.format_sql=true